# -*-coding:utf-8-*-

from collections import OrderedDict

class City:

    city_list = OrderedDict(
        [
            (u'台州', '578'),
            (u'哈尔滨', '5'),
            (u'天津', '3'),
            (u'佛山', '251'),
            (u'长沙', '206'),
            (u'丽江', '37'),
            (u'北京', '1'),
            (u'烟台', '533'),
            (u'福州', '258'),
            (u'西安', '10'),
            (u'济南', '144'),
            (u'三亚', '43'),
            (u'海口', '42'),
            (u'石家庄', '428'),
            (u'南昌', '376'),
            (u'南京', '12'),
            (u'绍兴', '22'),
            (u'南通', '82'),
            (u'广州', '32'),
            (u'太原', '105'),
            (u'大连', '6'),
            (u'贵阳', '38'),
            (u'苏州', '14'),
            (u'常州', '213'),
            (u'无锡', '13'),
            (u'厦门', '25'),
            (u'长春', '158'),
            (u'郑州', '559'),
            (u'昆明', '34'),
            (u'深圳', '30'),
            (u'宁波', '375'),
            (u'沈阳', '451'),
            (u'嘉兴', '571'),
            (u'威海', '479'),
            (u'合肥', '278'),
            (u'东莞', '223'),
            (u'成都', '28'),
            (u'重庆', '4'),
            (u'珠海', '31'),
            (u'杭州', '17'),
            (u'温州', '491'),
            (u'上海', '2'),
            (u'青岛', '7'),
            (u'武汉', '477')
        ]
    )
    city_list_bak = {u'无锡': '13',
                      u'台州': '578',
                      u'哈尔滨': '5',
                      u'厦门': '25',
                      u'长春': '158',
                      u'郑州': '559',
                      u'天津': '3',
                      u'昆明': '34',
                      u'佛山': '251',
                      u'宁波': '375',
                      u'长沙': '206',
                      u'沈阳': '451',
                      u'丽江': '37',
                      u'北京': '1',
                      u'嘉兴': '571',
                      u'烟台': '533',
                      u'福州': '258',
                      u'西安': '10',
                      u'上海': '2',
                      u'济南': '144',
                      u'三亚': '43',
                      u'海口': '42',
                      u'威海': '479',
                      u'东莞': '223',
                      u'石家庄': '428',
                      u'南昌': '376',
                      u'深圳': '30',
                      u'成都': '28',
                      u'绍兴': '22',
                      u'重庆': '4',
                      u'珠海': '31',
                      u'杭州': '17',
                      u'南通': '82',
                      u'广州': '32',
                      u'太原': '105',
                      u'温州': '491',
                      u'大连': '6',
                      u'南京': '12',
                      u'贵阳': '38',
                      u'青岛': '7',
                      u'苏州': '14',
                      u'常州': '213',
                      u'武汉': '477',
                      u'合肥': '278'}

    city_hotel_pingyin_bak = [(u'台州', 'http://hotels.ctrip.com/hotel/taizhou578'),
                              (u'哈尔滨', 'http://hotels.ctrip.com/hotel/haerbin5'),
                              (u'淄博', 'http://hotels.ctrip.com/hotel/zibo542'),
                              (u'天津', 'http://hotels.ctrip.com/hotel/tianjin3'),
                              (u'佛山', 'http://hotels.ctrip.com/hotel/foshan251'),
                              (u'长沙', 'http://hotels.ctrip.com/hotel/changsha206'),
                              (u'丽江', 'http://hotels.ctrip.com/hotel/lijiang37'),
                              (u'北京', 'http://hotels.ctrip.com/hotel/beijing1'),
                              (u'烟台', 'http://hotels.ctrip.com/hotel/yantai533'),
                              (u'福州', 'http://hotels.ctrip.com/hotel/fuzhou258'),
                              (u'西安', 'http://hotels.ctrip.com/hotel/xian10'),
                              (u'西宁', 'http://hotels.ctrip.com/hotel/xining124'),
                              (u'济南', 'http://hotels.ctrip.com/hotel/jinan144'),
                              (u'三亚', 'http://hotels.ctrip.com/hotel/sanya43'),
                              (u'海口', 'http://hotels.ctrip.com/hotel/haikou42'),
                              (u'镇江', 'http://hotels.ctrip.com/hotel/zhenjiang16'),
                              (u'泰州', 'http://hotels.ctrip.com/hotel/taizhou579'),
                              (u'石家庄', 'http://hotels.ctrip.com/hotel/shijiazhuang428'),
                              (u'南昌', 'http://hotels.ctrip.com/hotel/nanchang376'),
                              (u'南京', 'http://hotels.ctrip.com/hotel/nanjing12'),
                              (u'绍兴', 'http://hotels.ctrip.com/hotel/shaoxing22'),
                              (u'泰安', 'http://hotels.ctrip.com/hotel/taian454'),
                              (u'南通', 'http://hotels.ctrip.com/hotel/nantong82'),
                              (u'广州', 'http://hotels.ctrip.com/hotel/guangzhou32'),
                              (u'太原', 'http://hotels.ctrip.com/hotel/taiyuan105'),
                              (u'大连', 'http://hotels.ctrip.com/hotel/dalian6'),
                              (u'徐州', 'http://hotels.ctrip.com/hotel/xuzhou512'),
                              (u'贵阳', 'http://hotels.ctrip.com/hotel/guiyang38'),
                              (u'苏州', 'http://hotels.ctrip.com/hotel/suzhou14'),
                              (u'常州', 'http://hotels.ctrip.com/hotel/changzhou213'),
                              (u'济宁', 'http://hotels.ctrip.com/hotel/jining318'),
                              (u'惠州', 'http://hotels.ctrip.com/hotel/huizhou299'),
                              (u'金华', 'http://hotels.ctrip.com/hotel/jinhua308'),
                              (u'无锡', 'http://hotels.ctrip.com/hotel/wuxi13'),
                              (u'郑州', 'http://hotels.ctrip.com/hotel/zhengzhou559'),
                              (u'兰州', 'http://hotels.ctrip.com/hotel/lanzhou100'),
                              (u'扬州', 'http://hotels.ctrip.com/hotel/yangzhou15'),
                              (u'廊坊', 'http://hotels.ctrip.com/hotel/langfang340'),
                              (u'厦门', 'http://hotels.ctrip.com/hotel/xiamen25'),
                              (u'长春', 'http://hotels.ctrip.com/hotel/changchun158'),
                              (u'潍坊', 'http://hotels.ctrip.com/hotel/weifang475'),
                              (u'昆明', 'http://hotels.ctrip.com/hotel/kunming34'),
                              (u'深圳', 'http://hotels.ctrip.com/hotel/shenzhen30'),
                              (u'宁波', 'http://hotels.ctrip.com/hotel/ningbo375'),
                              (u'临沂', 'http://hotels.ctrip.com/hotel/linyi569'),
                              (u'嘉兴', 'http://hotels.ctrip.com/hotel/jiaxing571'),
                              (u'威海', 'http://hotels.ctrip.com/hotel/weihai479'),
                              (u'银川', 'http://hotels.ctrip.com/hotel/yinchuan99'),
                              (u'呼和浩特', 'http://hotels.ctrip.com/hotel/huhehaote103'),
                              (u'合肥', 'http://hotels.ctrip.com/hotel/hefei278'),
                              (u'乌鲁木齐', 'http://hotels.ctrip.com/hotel/wulumuqi39'),
                              (u'南宁', 'http://hotels.ctrip.com/hotel/nanning380'),
                              (u'东莞', 'http://hotels.ctrip.com/hotel/dongguan223'),
                              (u'成都', 'http://hotels.ctrip.com/hotel/chengdu28'),
                              (u'重庆', 'http://hotels.ctrip.com/hotel/chongqing4'),
                              (u'珠海', 'http://hotels.ctrip.com/hotel/zhuhai31'),
                              (u'杭州', 'http://hotels.ctrip.com/hotel/hangzhou17'),
                              (u'温州', 'http://hotels.ctrip.com/hotel/wenzhou491'),
                              (u'马鞍山', "http://hotels.ctrip.com/hotel/ma'anshan1024"),
                              (u'上海', 'http://hotels.ctrip.com/hotel/shanghai2'),
                              (u'青岛', 'http://hotels.ctrip.com/hotel/qingdao7'),
                              (u'沈阳', 'http://hotels.ctrip.com/hotel/shenyang451'),
                              (u'武汉', 'http://hotels.ctrip.com/hotel/wuhan477')
                              ]



    city_hotel_pingyin = {
        u'沈阳': 'http://hotels.ctrip.com/hotel/shenyang451',
        u'无锡': 'http://hotels.ctrip.com/hotel/wuxi13',
        u'台州': 'http://hotels.ctrip.com/hotel/taizhou578',
        u'哈尔滨': 'http://hotels.ctrip.com/hotel/haerbin5',
        u'扬州': 'http://hotels.ctrip.com/hotel/yangzhou15',
        u'淄博': 'http://hotels.ctrip.com/hotel/zibo542',
        u'廊坊': 'http://hotels.ctrip.com/hotel/langfang340',
        u'厦门': 'http://hotels.ctrip.com/hotel/xiamen25',
        u'兰州': 'http://hotels.ctrip.com/hotel/lanzhou100',
        u'青岛': 'http://hotels.ctrip.com/hotel/qingdao7',
        u'临沂': 'http://hotels.ctrip.com/hotel/linyi569',
        u'长春': 'http://hotels.ctrip.com/hotel/changchun158',
        u'昆明': 'http://hotels.ctrip.com/hotel/kunming34',
        u'佛山': 'http://hotels.ctrip.com/hotel/foshan251',
        u'宁波': 'http://hotels.ctrip.com/hotel/ningbo375',
        u'长沙': 'http://hotels.ctrip.com/hotel/changsha206',
        u'天津': 'http://hotels.ctrip.com/hotel/tianjin3',
        u'丽江': 'http://hotels.ctrip.com/hotel/lijiang37',
        u'北京': 'http://hotels.ctrip.com/hotel/beijing1',
        u'嘉兴': 'http://hotels.ctrip.com/hotel/jiaxing571',
        u'烟台': 'http://hotels.ctrip.com/hotel/yantai533',
        u'福州': 'http://hotels.ctrip.com/hotel/fuzhou258',
        u'马鞍山': "http://hotels.ctrip.com/hotel/ma'anshan1024",
        u'西安': 'http://hotels.ctrip.com/hotel/xian10',
        u'上海': 'http://hotels.ctrip.com/hotel/shanghai2',
        u'东莞': 'http://hotels.ctrip.com/hotel/dongguan223',
        u'银川': 'http://hotels.ctrip.com/hotel/yinchuan99',
        u'西宁': 'http://hotels.ctrip.com/hotel/xining124',
        u'济南': 'http://hotels.ctrip.com/hotel/jinan144',
        u'乌鲁木齐': 'http://hotels.ctrip.com/hotel/wulumuqi39',
        u'三亚': 'http://hotels.ctrip.com/hotel/sanya43',
        u'海口': 'http://hotels.ctrip.com/hotel/haikou42',
        u'威海': 'http://hotels.ctrip.com/hotel/weihai479',
        u'南宁': 'http://hotels.ctrip.com/hotel/nanning380',
        u'镇江': 'http://hotels.ctrip.com/hotel/zhenjiang16',
        u'泰州': 'http://hotels.ctrip.com/hotel/taizhou579',
        u'石家庄': 'http://hotels.ctrip.com/hotel/shijiazhuang428',
        u'南昌': 'http://hotels.ctrip.com/hotel/nanchang376',
        u'深圳': 'http://hotels.ctrip.com/hotel/shenzhen30',
        u'成都': 'http://hotels.ctrip.com/hotel/chengdu28',
        u'绍兴': 'http://hotels.ctrip.com/hotel/shaoxing22',
        u'重庆': 'http://hotels.ctrip.com/hotel/chongqing4',
        u'珠海': 'http://hotels.ctrip.com/hotel/zhuhai31',
        u'潍坊': 'http://hotels.ctrip.com/hotel/weifang475',
        u'泰安': 'http://hotels.ctrip.com/hotel/taian454',
        u'南通': 'http://hotels.ctrip.com/hotel/nantong82',
        u'广州': 'http://hotels.ctrip.com/hotel/guangzhou32',
        u'太原': 'http://hotels.ctrip.com/hotel/taiyuan105',
        u'温州': 'http://hotels.ctrip.com/hotel/wenzhou491',
        u'大连': 'http://hotels.ctrip.com/hotel/dalian6',
        u'南京': 'http://hotels.ctrip.com/hotel/nanjing12',
        u'徐州': 'http://hotels.ctrip.com/hotel/xuzhou512',
        u'贵阳': 'http://hotels.ctrip.com/hotel/guiyang38',
        u'郑州': 'http://hotels.ctrip.com/hotel/zhengzhou559',
        u'苏州': 'http://hotels.ctrip.com/hotel/suzhou14',
        u'常州': 'http://hotels.ctrip.com/hotel/changzhou213',
        u'呼和浩特': 'http://hotels.ctrip.com/hotel/huhehaote103',
        u'济宁': 'http://hotels.ctrip.com/hotel/jining318',
        u'武汉': 'http://hotels.ctrip.com/hotel/wuhan477',
        u'合肥': 'http://hotels.ctrip.com/hotel/hefei278',
        u'惠州': 'http://hotels.ctrip.com/hotel/huizhou299',
        u'杭州': 'http://hotels.ctrip.com/hotel/hangzhou17',
        u'金华': 'http://hotels.ctrip.com/hotel/jinhua308'}

    district = {
        u'无锡': {
            u'梁溪区': '504', u'滨湖区': '501', u'惠山区': '959', u'锡山区': '500'},
        u'台州': {
            u'路桥区': '469', u'椒江区': '468', u'黄岩区': '467'},
        u'哈尔滨': {
            u'阿城区': '2395', u'道里区': '347', u'双城区': '2078', u'平房区': '1134', u'南岗区': '346',
            u'道外区': '348', u'呼兰区': '2394', u'香坊区': '349', u'松北区': '1015'},
        u'厦门': {
            u'翔安区': '1008', u'集美区': '12', u'思明区': '15', u'湖里区': '144', u'同安区': '11', u'海沧区': '480'},
        u'长春': {
            u'绿园区': '517', u'宽城区': '515', u'朝阳区': '513', u'二道区': '516', u'南关区': '514', u'双阳区': '1232'},
        u'青岛': {
            u'崂山区': '405', u'市北区': '322', u'城阳区': '2381', u'黄岛区': '771', u'市南区': '323', u'李沧区': '406'},
        u'天津': {
            u'蓟州区': '1357', u'东丽区': '313', u'宁河区': '1342', u'南开区': '317', u'北辰区': '865', u'和平区': '147',
            u'河西区': '308', u'静海区': '1398', u'红桥区': '977', u'津南区': '1109', u'河北区': '341', u'西青区': '1175',
            u'滨海新区': '842', u'河东区': '314', u'大港区': '311', u'武清区': '312', u'宝坻区': '446'},
        u'昆明': {
            u'官渡区': '138', u'盘龙区': '135', u'东川区': '1615', u'五华区': '137', u'呈贡区': '1616', u'西山区': '136'},
        u'佛山': {
            u'禅城区': '289', u'高明区': '403', u'三水区': '402', u'顺德区': '401', u'南海区': '400'},
        u'宁波': {
            u'北仑区': '478', u'江北区': '450', u'海曙区': '448', u'高新区': '1188', u'鄞州区': '479', u'江东区': '449',
            u'镇海区': '494'},
        u'长沙': {
            u'雨花区': '482', u'望城区': '1370', u'岳麓区': '484', u'天心区': '483', u'开福区': '485', u'芙蓉区': '481'},
        u'沈阳': {
            u'大东区': '422', u'苏家屯区': '1226', u'沈北新区': '1369', u'铁西区': '423', u'皇姑区': '148',
            u'沈河区': '421', u'于洪区': '424', u'和平区': '420', u'浑南区': '426'},
        u'北京': {
            u'西城区': '92', u'怀柔区': '102', u'石景山区': '97', u'通州区': '108', u'顺义区': '98', u'门头沟区': '130',
            u'密云区': '103', u'平谷区': '106', u'朝阳区': '94', u'海淀区': '96', u'东城区': '93', u'丰台区': '101',
            u'大兴区': '105', u'昌平区': '104', u'房山区': '95', u'延庆区': '109'},
        u'嘉兴': {
            u'南湖区': '694', u'秀洲区': '695'},
        u'烟台': {
            u'牟平区': '1352', u'芝罘区': '743', u'福山区': '1356', u'莱山区': '744'},
        u'福州': {
            u'晋安区': '327', u'马尾区': '1397', u'台江区': '416', u'鼓楼区': '326', u'仓山区': '417'},
        u'威海': {
            u'文登区': '2204', u'环翠区': '740'},
        u'上海': {
            u'闵行区': '122', u'虹口区': '116', u'杨浦区': '121', u'奉贤区': '133', u'黄浦区': '115', u'崇明区': '134',
            u'普陀区': '120', u'静安区（原闸北区）': '118', u'宝山区': '117', u'长宁区': '114', u'浦东新区': '119',
            u'松江区': '125', u'青浦区': '128', u'嘉定区': '123', u'金山区': '126', u'徐汇区': '113', u'静安区': '112'},
        u'合肥': {
            u'双凤工业区': '2408', u'滨湖新区': '2406', u'瑶海区': '488', u'经济开发区': '2407', u'蜀山区': '490',
            u'包河区': '489', u'政务区': '2405', u'庐阳区': '487'},
        u'三亚': {
            u'吉阳区': '1243', u'天涯区': '1335', u'市中心': '27', u'崖州区': '2113', u'远海市郊': '29', u'海棠区': '2114',
            u'三亚湾海坡开发区': '958', u'海滨': '28'},
        u'海口': {
            u'秀英区': '20', u'琼山区': '419', u'龙华区': '18', u'美兰区': '19'},
        u'西安': {
            u'新城区': '171', u'灞桥区': '1049', u'长安区': '179', u'未央区': '175', u'碑林区': '172', u'阎良区': '1532',
            u'临潼区': '939', u'莲湖区': '173', u'雁塔区': '174'},
        u'东莞': {
            u'寮步镇': '1333', u'东坑镇': '2434', u'虎门镇': '459', u'长安镇': '462', u'桥头镇': '463', u'莞城': '460',
            u'高埗镇': '465', u'大朗镇': '531', u'石排镇': '2439', u'万江区': '527', u'大岭山镇': '530', u'清溪镇': '948',
            u'凤岗镇': '477', u'黄江镇': '472', u'沙田镇': '2438', u'樟木头镇': '366', u'石龙镇': '475', u'横沥镇': '2435',
            u'中堂镇': '2441', u'塘厦镇': '464', u'厚街镇': '461', u'企石镇': '2437', u'谢岗镇': '1349', u'南城区': '529',
            u'松山湖科技产业园区': '640', u'望牛墩镇': '2440', u'石碣镇': '639', u'道滘镇': '2433', u'麻涌镇': '2436',
            u'洪梅镇': '471', u'东城区': '528', u'茶山镇': '525', u'常平镇': '476'},
        u'石家庄': {
            u'栾城区': '2088', u'新华区': '862', u'长安区': '852', u'桥西区': '854', u'裕华区': '855', u'井陉矿区': '2116',
            u'藁城区': '2084', u'鹿泉区': '2085'},
        u'南昌': {
            u'新建区': '2480', u'青云谱区': '769', u'青山湖区': '540', u'西湖区': '768', u'湾里区': '1519', u'东湖区': '701'},
        u'深圳': {
            u'罗湖区': '215', u'宝安区': '214', u'南山区': '213', u'龙岗区': '211', u'福田区': '207', u'盐田区': '209'},
        u'成都': {
            u'金牛区': '385', u'成华区': '395', u'青白江区': '1154', u'新都区': '1122', u'青羊区': '270', u'武侯区': '390',
            u'龙泉驿区': '382', u'双流区': '2472', u'锦江区': '396', u'温江区': '916'},
        u'绍兴': {
            u'越城区': '578', u'上虞区': '1604', u'柯桥区': '696'},
        u'重庆': {
            u'沙坪坝区': '452', u'城口': '2006', u'南岸区': '455', u'黔江区': '1228', u'涪陵区': '1185', u'渝中区': '454',
            u'奉节': '2009', u'垫江': '2007', u'忠县': '2022', u'潼南': '2015', u'巴南区': '458', u'开州区': '2010',
            u'北碚区': '978', u'永川区': '1176', u'巫溪': '2017', u'酉阳': '2020', u'大足区': '1227', u'彭水': '2012',
            u'梁平': '2011', u'秀山': '2019', u'合川区': '1386', u'渝北区': '992', u'云阳': '2021', u'武隆': '2018',
            u'铜梁区': '1996', u'江津区': '1147', u'万州区': '486', u'九龙坡区': '451', u'大渡口区': '1077', u'江北区': '456',
            u'石柱': '2014', u'荣昌': '2013', u'丰都': '2008', u'南川区': '1374', u'巫山': '2016', u'璧山区': '1997',
            u'綦江区': '1233', u'长寿区': '1368'},
        u'珠海': {
            u'香洲区': '538', u'金湾区': '637', u'斗门区': '636'},
        u'杭州': {
            u'千岛湖': '2397', u'上城区': '408', u'余杭区': '415', u'滨江区': '413', u'下城区': '409', u'萧山区': '414',
            u'西湖区': '410', u'江干区': '412', u'拱墅区': '411', u'富阳区': '2083'},
        u'南通': {
            u'崇川区': '624', u'港闸区': '999', u'通州区': '1261'},
        u'广州': {
            u'天河区': '142', u'越秀区': '375', u'增城区': '228', u'白云区': '230', u'从化区': '232', u'南沙区': '141',
            u'黄埔区': '233', u'花都区': '303', u'番禺区': '256', u'海珠区': '373', u'荔湾区': '374'},
        u'太原': {
            u'杏花岭区': '821', u'晋源区': '823', u'万柏林区': '1144', u'小店区': '822', u'迎泽区': '820',
            u'尖草坪区': '1016'},
        u'温州': {
            u'鹿城区': '168', u'洞头区': '2469', u'龙湾区': '369', u'瓯海区': '169'},
        u'大连': {
            u'西岗区': '343', u'旅顺口区': '1237', u'甘井子区': '340', u'高新园区': '1437', u'中山区': '342',
            u'金州区': '1055', u'沙河口区': '146'},
        u'南京': {
            u'建邺区': '186', u'玄武区': '377', u'高淳区': '1595', u'秦淮区': '181', u'浦口区': '187', u'栖霞区': '184',
            u'江宁区': '180', u'六合区': '1046', u'鼓楼区': '188', u'溧水区': '1596', u'雨花台区': '182'},
        u'贵阳': {
            u'观山湖区': '1255', u'白云区': '1355', u'花溪区': '1208', u'云岩区': '520', u'南明区': '521', u'乌当区': '1223'},
        u'郑州': {
            u'上街区': '1337', u'惠济区': '1582', u'金水区': '438', u'二七区': '437', u'中原区': '436',
            u'管城回族区': '596', u'郑东新区': '2471'},
        u'苏州': {
            u'吴江区': '1593', u'吴中区': '193', u'相城区': '189', u'姑苏区': '1485', u'虎丘区': '191'},
        u'常州': {
            u'金坛区': '2477', u'武进区': '495', u'新北区': '496', u'戚墅堰区': '1407', u'天宁区': '497', u'钟楼区': '498'},
        u'武汉': {
            u'汉阳区': '307', u'武昌区': '306', u'江汉区': '305', u'蔡甸区': '433', u'青山区': '430', u'江夏区': '1510',
            u'黄陂区': '443', u'洪山区': '431', u'江岸区': '428', u'东西湖区': '432', u'汉南区': '1225', u'硚口区': '429',
            u'新洲区': '1545'},
        u'济南': {
            u'天桥区': '509', u'槐荫区': '508', u'历城区': '510', u'长清区': '1401', u'历下区': '506', u'市中区': '507'},
        u'丽江': {
            u'古城区': '287'}
    }